### PR TITLE
Added support for the goo.gl shortener.

### PR DESCRIPTION
**Pull request by mbeijen**
I added support for the goo.gl service.

BTW did you forget to add the `Changes` file to the git repo? It is on CPAN but not the repository.
## 

Mike

### CODE REVIEW

**Comment by mbeijen** [comment]
The travis build fails on some perls because tinyurl tests fail sometimes. This is basically because of tinyurl and not because of this module. See also https://rt.cpan.org/Public/Bug/Display.html?id=88052

**Comment by mbeijen** [comment]
aw crap! Namespace collission ahead. See https://github.com/yappo/p5-WWW-Shorten-Google/issues/3 - your suggestions are welcome!

**Comment by davorg** [comment]
The model I'm trying to move to for WWW::Shorten is that the individual shortener modules live in their own CPAN distributions - and they just depend on the main WWW::Shorten distribution which contains all of the scaffolding. Clearly, I haven't reached tht goal yet and there are still a number of shortener modules which need to be removed from the main distribution. But I'm not going to add any more shortener modules to the main distribution.

So it looks like you'll need to sort this out with the maintainer of the existing WWW::Shorten::Google module. I'm not going to merge this pull request.

**Comment by mbeijen** [comment]
Thanks for your feedback and I understand your reasoning.

The downside I see to this is for packaging. WWW::Shorten is available in
Fedora, EPEL for RHEL and CentOS, and Debian/Ubuntu. If the module does not
ship with actual shorteners, and these are not part of the downstream
distributions, having WWW::Shorten is not going to have much value all by
itself. In other words, bundling the modules in one distribution is a nice
way of 'smuggling' the modules into the Linux distros.

## 

Mike

Op zondag 4 januari 2015 heeft Dave Cross <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> het volgende
geschreven:

**Comment by davorg** [comment]
Yeah, sorry, I should be clearer.

My plan was that WWW::Shorten would end up containing just one "reference implementation" of a shortener - so it could be used to shorten URLs without any other distributions being necessary.

The main problem, of course, would be choosing which implementation to bundle in the distribution.

**Pull request closed without merging**
